version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  publish:
    docker:
      - image: alpine
    environment:
      - APP_ID: odpbomaebbohfliiicakdndlbjmeceoa
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apk add --no-cache \
            curl \
            jq \
            nodejs \
            npm \
            zip
      - run:
          name: "Install NPM Packages"
          command: |
            npm install && npm run build
      - run:
          name: "Package Extension"
          command: zip -r little-pause.zip dist
      - run:
          name: "Upload & Publish Extension to the Google Chrome Store"
          command: |
            echo "Did you remember to update the manifest version number?"
            ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T little-pause.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"

workflows:
  test-and-publish:
    jobs:
      - node/test
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - node/test
